### ISSUE TITLE
Input table does not accommodate additional columns from pasted source

### ISSUE THREAD

**Issue by ChadLevy** [lorefnon/plain-text-table#3]
When pasting from a table whose columns exceed the default 5 columns, the additional columns are truncated.

**To reproduce:**

1. Have a table whose columns exceed the default columns (5), for example (6 columns)
![image](https://cloud.githubusercontent.com/assets/909190/6518839/a648183a-c360-11e4-92ec-ccbc2276c659.png)

2. Copy and paste the table into "Your table"
![image](https://cloud.githubusercontent.com/assets/909190/6518864/1186de88-c361-11e4-9c7d-db85953356e6.png)

**Expected:**
The table should expand to accommodate the 6th column "Dislikes"

**Actual:**
The 6th column "Dislikes" is truncated.

    ┌──────┬──────┬────────────┬────────────────────────────┬────────┐
    │First │Last  │Nick        │Company                     │Likes   │
    ├──────┼──────┼────────────┼────────────────────────────┼────────┤
    │Austin│Powers│Powers Booth│Her Majesty's Secret Service│Shagging│
    ├──────┼──────┼────────────┼────────────────────────────┼────────┤

**Work-around:**
Right-click on "Your table" and select "Insert column..."

![image](https://cloud.githubusercontent.com/assets/909190/6518931/05a97b60-c362-11e4-8820-5a00d7289c9d.png)

**Comment by lorefnon** [comment]
Thanks for pointing this out. This should be resolved now.

Please verify that this works as expected. We can close the issue then.

**Comment by ChadLevy** [comment]
It's working! Awesome!
