### ISSUE TITLE
Output contains empty rows

### ISSUE THREAD

**Issue by jmini** [lorefnon/plain-text-table#8]
Empty rows at the bottom of the table should not be generated in the output.

Current output:

    ┌────┬────┐
    │This│is  │
    ├────┼────┤
    │a   │test│
    ├────┼────┤
    ├────┼────┤
    ├────┼────┤
    └────┴────┘

It should be consistent with the empty columns (on the right of the table) that are ignored.

Expected:

    ┌────┬────┐
    │This│is  │
    ├────┼────┤
    │a   │test│
    └────┴────┘

Of course if a value is set in the middle of the table, rows on top and column on the left should be generated.

This is valid:

    ┌┬────┐
    ├┼────┤
    ││XXXX│
    └┴────┘

**Comment by jmini** [comment]
Fixed, see http://lorefnon.me/plain-text-table/

**Comment by lorefnon** [comment]
There seem to be some inconsistencies regarding this. For instance:

![screen shot 2015-04-18 at 3 43 25 pm](https://cloud.githubusercontent.com/assets/1449492/7215017/c81078ec-e5e1-11e4-85cb-2d9051328a34.png)


I am re-opening this for now. Hopefully I'll get the time to look into it in a day or two.

**Comment by jmini** [comment]
Yes thank you for that. I have noticed when I was working on #2. I have fixed it on my [patch6](https://github.com/jmini/plain-text-table/tree/patch6) branch (for the moment published here: http://jmini.github.io/plain-text-table/).

I will close #2 and #8 in one single commit (corresponding to the changes made on the patch6).

Thank you for your tests.

**Comment by jmini** [comment]
Error detected by @lorefnon was fixed with commit 907886d19387ceef0c92ff38b428015b3460e6ee (fix for #2).

**Comment by lorefnon** [comment]
Great work. Thanks a lot :)
