### ISSUE TITLE
Additional styling option

### ISSUE THREAD

**Issue by jmini** [lorefnon/plain-text-table#9]
On *webapps.stackexchange.com* the user *Lipis* is [suggesting](http://webapps.stackexchange.com/a/6709/90399) an output looking like this:

A]

     ╔══════╤═══════════╤════════╗
     ║  ID  │ Name      │  Age   ║ 
     ╠══════╪═══════════╪════════╣
     ║  1   │ John      │   24   ║ 
     ╟──────┼───────────┼────────╢
     ║  2   │ Jeff      │   19   ║ 
     ╟──────┼───────────┼────────╢
     ║  3   │ Joel      │   42   ║ 
     ╚══════╧═══════════╧════════╝

This other [source](http://ozh.github.io/ascii-tables/) of inspiration propose:
B]

    +====+======+=====+
    | ID | Name | Age |
    +====+======+=====+
    |  1 | John |  24 |
    +----+------+-----+
    |  2 | Jeff |  19 |
    +----+------+-----+
    |  3 | Joel |  42 |
    +----+------+-----+

C]

      ID   Name   Age  
     ---- ------ ----- 
       1   John    24  
       2   Jeff    19  
       3   Joel    42  

D]

    | ID | Name | Age |
    |----|------|-----|
    |  1 | John |  24 |
    |  2 | Jeff |  19 |
    |  3 | Joel |  42 |

**Comment by jmini** [comment]
For the Unicode implementation, this wikipedia page is useful:
http://en.wikipedia.org/wiki/Box-drawing_character

**Comment by jmini** [comment]
The two concepts 

* Type 
* Style

introduced with pull requests #4 and #5 are not sufficient if we want to provide all those possibilities.

I am working a new concept with more options (see bellow). We could provide an additional combobox to set the options for some predefined style. 

________

## Charset option

* Unicode
* Ascii

## Headers option

### Horizontal Header:

Type of column headers.

* __None__: No header. The first line is directly the content.
* __First line__: The first line of the table is used as header.
* __Number__: number are used as column header.
* __Letter__: letters are used as column header (A, B, C.. - like in Excel).


### Vertical Header:

Type of line headers.

* __None__: No header. The first column is directly the content.
* __First column__: The first column of the table is used as header.
* __Number__: number are used as line header (1, 2, 3.. - like in Excel).
* __Letter__: letters are used as line header.

## Borders option

For each border you can select:

* __None__: no border at all
* __Single__: single border
* __Double__: double border

Depending on the char set (Unicode or ASCII) some combinations are not possible.

### Horizontal Top Border

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ║   ║   Name    │ First Name │ Track Id │ Checked ║
    ╠═══╬═══════════╪════════════╪══════════╪═════════╣
    ║ 1 ║ Sheffield │ Alice      │      347 │   yes   ║
    ╟───╫───────────┼────────────┼──────────┼─────────╢
    ║   ║           │ Carrie,    │          │         ║
    ║ 2 ║ Smith     │ Bob and    │      152 │         ║
    ║   ║           │ Friends    │          │         ║
    ╟───╫───────────┼────────────┼──────────┼─────────╢
    ║ 3 ║ Samson    │ Dick       │      948 │   yes   ║
    ╚═══╩═══════════╧════════════╧══════════╧═════════╝

### Horizontal Inner Header Border

    ╔═══╦═══════════╤════════════╤══════════╤═════════╗
    ║   ║   Name    │ First Name │ Track Id │ Checked ║
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ║ 1 ║ Sheffield │ Alice      │      347 │   yes   ║
    ╟───╫───────────┼────────────┼──────────┼─────────╢
    ║   ║           │ Carrie,    │          │         ║
    ║ 2 ║ Smith     │ Bob and    │      152 │         ║
    ║   ║           │ Friends    │          │         ║
    ╟───╫───────────┼────────────┼──────────┼─────────╢
    ║ 3 ║ Samson    │ Dick       │      948 │   yes   ║
    ╚═══╩═══════════╧════════════╧══════════╧═════════╝

This border is only present if a column headers are defined (`horizontal header` set to `first line`, `number` or `letter`).

### Horizontal Inner Border

    ╔═══╦═══════════╤════════════╤══════════╤═════════╗
    ║   ║   Name    │ First Name │ Track Id │ Checked ║
    ╠═══╬═══════════╪════════════╪══════════╪═════════╣
    ║ 1 ║ Sheffield │ Alice      │      347 │   yes   ║
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ║   ║           │ Carrie,    │          │         ║
    ║ 2 ║ Smith     │ Bob and    │      152 │         ║
    ║   ║           │ Friends    │          │         ║
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ║ 3 ║ Samson    │ Dick       │      948 │   yes   ║
    ╚═══╩═══════════╧════════════╧══════════╧═════════╝

### Horizontal Bottom Border

    ╔═══╦═══════════╤════════════╤══════════╤═════════╗
    ║   ║   Name    │ First Name │ Track Id │ Checked ║
    ╠═══╬═══════════╪════════════╪══════════╪═════════╣
    ║ 1 ║ Sheffield │ Alice      │      347 │   yes   ║
    ╟───╫───────────┼────────────┼──────────┼─────────╢
    ║   ║           │ Carrie,    │          │         ║
    ║ 2 ║ Smith     │ Bob and    │      152 │         ║
    ║   ║           │ Friends    │          │         ║
    ╟───╫───────────┼────────────┼──────────┼─────────╢
    ║ 3 ║ Samson    │ Dick       │      948 │   yes   ║
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

### Vertical Left Border

    X═══╦═══════════╤════════════╤══════════╤═════════╗
    X   ║   Name    │ First Name │ Track Id │ Checked ║
    X═══╬═══════════╪════════════╪══════════╪═════════╣
    X 1 ║ Sheffield │ Alice      │      347 │   yes   ║
    X───╫───────────┼────────────┼──────────┼─────────╢
    X   ║           │ Carrie,    │          │         ║
    X 2 ║ Smith     │ Bob and    │      152 │         ║
    X   ║           │ Friends    │          │         ║
    X───╫───────────┼────────────┼──────────┼─────────╢
    X 3 ║ Samson    │ Dick       │      948 │   yes   ║
    X═══╩═══════════╧════════════╧══════════╧═════════╝

### Vertical Inner Header Border

    ╔═══X═══════════╤════════════╤══════════╤═════════╗
    ║   X   Name    │ First Name │ Track Id │ Checked ║
    ╠═══X═══════════╪════════════╪══════════╪═════════╣
    ║ 1 X Sheffield │ Alice      │      347 │   yes   ║
    ╟───X───────────┼────────────┼──────────┼─────────╢
    ║   X           │ Carrie,    │          │         ║
    ║ 2 X Smith     │ Bob and    │      152 │         ║
    ║   X           │ Friends    │          │         ║
    ╟───X───────────┼────────────┼──────────┼─────────╢
    ║ 3 X Samson    │ Dick       │      948 │   yes   ║
    ╚═══X═══════════╧════════════╧══════════╧═════════╝

This border is only present if line headers are defined (`vertical header` set to `first column`, `number` or `letter`).

### Vertical Inner Border

    ╔═══╦═══════════X════════════X══════════X═════════╗
    ║   ║   Name    X First Name X Track Id X Checked ║
    ╠═══╬═══════════X════════════X══════════X═════════╣
    ║ 1 ║ Sheffield X Alice      X      347 X   yes   ║
    ╟───╫───────────X────────────X──────────X─────────╢
    ║   ║           X Carrie,    X          X         ║
    ║ 2 ║ Smith     X Bob and    X      152 X         ║
    ║   ║           X Friends    X          X         ║
    ╟───╫───────────X────────────X──────────X─────────╢
    ║ 3 ║ Samson    X Dick       X      948 X   yes   ║
    ╚═══╩═══════════X════════════X══════════X═════════╝

### Vertical Bottom Border

    ╔═══╦═══════════╤════════════╤══════════╤═════════X
    ║   ║   Name    │ First Name │ Track Id │ Checked X
    ╠═══╬═══════════╪════════════╪══════════╪═════════X
    ║ 1 ║ Sheffield │ Alice      │      347 │   yes   X
    ╟───╫───────────┼────────────┼──────────┼─────────X
    ║   ║           │ Carrie,    │          │         X
    ║ 2 ║ Smith     │ Bob and    │      152 │         X
    ║   ║           │ Friends    │          │         X
    ╟───╫───────────┼────────────┼──────────┼─────────X
    ║ 3 ║ Samson    │ Dick       │      948 │   yes   X
    ╚═══╩═══════════╧════════════╧══════════╧═════════X

________

This can be tested live on my fork:
http://jmini.github.io/plain-text-table/

**Comment by jmini** [comment]
All Ascii table styles supported by @ozh project [ozh/ascii-tables](https://github.com/ozh/ascii-tables) are now possible with PlainTextTable ([tool online](http://lorefnon.me/plain-text-table/), [source on GitHub](https://github.com/lorefnon/plain-text-table))

**Comment by ozh** [comment]
:+1: :)

**Comment by lorefnon** [comment]
This is quite awesome. Great work :)
